### ISSUE TITLE
Add more region info

### ISSUE THREAD

**Issue by liuchang0812** [tencentyun/cos-python-sdk-v4#15]

**Comment by v2leon** [comment]
Buket如果是“华北地区”的……sdk就不好使了，region限定shanghai/guangzhou....

**Comment by liuchang0812** [comment]
@v2leon SDK 可以传入自定义的region host

**Comment by liuchang0812** [comment]
@v2leon 

https://github.com/tencentyun/cos-python-sdk-v4/blob/master/qcloud_cos/cos_config.py#L20

使用方式如下：

``` python
client = CosClient(appid, accessid, accesskey, hostname='', download_hostname='')
```

**Comment by liuchang0812** [comment]
@v2leon 已经添加天津

**Comment by v2leon** [comment]
谢谢已经解决
