### ISSUE TITLE
目录操作异常

### ISSUE THREAD

**Issue by chz34** [tencentyun/cos-python-sdk-v4#23]
直接使用上传服务`upload_file`时可以在`cos_path`中使用多层路径，对于不存在的目录，系统会自动创建。

但是使用这种方法自动创建的目录无法被`stat_folder`接口访问到，会返回404错误。

需要重新使用`create_folder`方法重新创建一次目录，之后能够被`stat_folder`接口访问到。

**Comment by liuchang0812** [comment]
By design.
