### ISSUE TITLE
fail to upload slice file

### ISSUE THREAD

**Issue by DeoLeung** [tencentyun/cos-python-sdk-v4#30]
```bash
2017-05-13 23:04:33.905 connectionpool:7453 DEBUG http://gz.file.myqcloud.com:80 "POST /files/v2/11111/bucket/log HTTP/1.1" 400 343
*** <?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>InvalidRequest</Code>
	<Message>Missing required header for this request: Appid</Message>
	<Resource>-..myqcloud.com/files/v2/1111/bucket/log</Resource>
	<RequestId>NTkxNzIwODFfY2JhMzNiXzM0ZDhfZjU3MzVk</RequestId>
	<TraceId/>
</Error>
```

I don't see we need `Appid` in headers

**Comment by DeoLeung** [comment]
also the api return xml, not json...

**Comment by liuchang0812** [comment]
hi, how could you get this? did you use this SDK?

**Comment by DeoLeung** [comment]
@Liuchang0812 
yes, using `UploadSliceFileRequest` along with `client.upload_file` for a large file, about 700MB
I manually constructed a request to the api, checked that was the JSON API error https://www.qcloud.com/document/api/436/606

**Comment by liuchang0812** [comment]
well, thank you very much! I will check it now

**Comment by liuchang0812** [comment]
@DeoLeung 

Hi, we could re-produce this problem, and we will fix this problem in next release. thanks for your work. BTW, your `appid` and `bucket` is mistake. you cloud use service normally if you correct your `appid`.

please let me know if you still have problem. :+1:

**Comment by DeoLeung** [comment]
@Liuchang0812 
I miss use the bucket 'domain name' as 'name', replacing it works fine

thank you
